# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d329a61a455bb5d2435454b88440931e88d09737fcd0568593159fdac184e3e3e42bf8b4f9a4c7d88481492d3fa674c73c5cb1d1fb5370572750981b22f21ca9

test:
  secret_key_base: 685469ab4d5594915c3938fbfe230b8f1ca4fa478f046b5ae1abf89fd0b7662986c48c511638100f3c2dcfcf7b800082be2a50bdd87b6205e78988fe5f935017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
